#!/usr/bin/env python
# Builds the dissent_native GDExtension into ../bin, where extension/dissent_native.gdextension
# looks for it. Run through tools/build_native.sh rather than directly; options are godot-cpp's
# (target=template_debug|template_release, platform=..., arch=...).
import os

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "../bin/libdissent_native{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
Default(library)
