class_name SpecGenerators
extends RefCounted

## Writes the generated artifacts derived from the spec registry:
##   scripts/generated/entity_ids.gd         — EntityIds consts (pieces)
##   scripts/generated/status_effect_ids.gd  — StatusEffectIds consts
##   resources/generated/technology.json     — cost / build time / requires
##   resources/generated/tools.json          — build/train tool registry
## Everything is emitted in alphabetical id order (per user convention — ids are
## named so alphabetical grouping is meaningful). All files carry AUTO-GENERATED
## headers; hand edits belong in the gdd docs, not here.

const ENTITY_IDS_PATH: String = "res://scripts/generated/entity_ids.gd"
const STATUS_EFFECT_IDS_PATH: String = "res://scripts/generated/status_effect_ids.gd"
const TECHNOLOGY_PATH: String = "res://resources/generated/technology.json"
const TOOLS_PATH: String = "res://resources/generated/tools.json"

const TICKS_PER_SECOND: int = 30


## Writes all four artifacts. Returns the list of written paths.
static func generate_all(a_registry: RefCounted) -> Array:
	var written: Array = []
	written.append(_write(ENTITY_IDS_PATH, entity_ids_text(a_registry)))
	written.append(_write(STATUS_EFFECT_IDS_PATH, status_effect_ids_text(a_registry)))
	written.append(_write(TECHNOLOGY_PATH, technology_json(a_registry)))
	written.append(_write(TOOLS_PATH, tools_json(a_registry)))
	return written


static func entity_ids_text(a_registry: RefCounted) -> String:
	var out: String = _gd_header("game-piece id constants")
	out += "class_name EntityIds\n\n"
	out += "## One StringName const per game piece defined in the gdd docs. Reference\n"
	out += "## pieces through these in hand-written code (typo-safe, autocompletes);\n"
	out += "## scenes and data files store the raw StringName.\n\n"
	var ids: Array = a_registry.pieces.keys()
	ids.sort()
	for id in ids:
		out += "const %s := &\"%s\"\n" % [String(id).to_upper(), id]
	return out


static func status_effect_ids_text(a_registry: RefCounted) -> String:
	var out: String = _gd_header("status-effect id constants")
	out += "class_name StatusEffectIds\n\n"
	out += "## One StringName const per registered status effect (kind: status_effect\n"
	out += "## docs). The id maps to the effect scene referenced by projectiles.\n\n"
	var ids: Array = a_registry.status_effects.keys()
	ids.sort()
	for id in ids:
		out += "const %s := &\"%s\"\n" % [String(id).to_upper(), id]
	if ids.is_empty():
		out += "# (no status effects registered yet)\n"
	return out


## {id: {"cost": {...}, "build_time_ticks": int, "requires": [...]}} for every
## piece with economy data (a cost: key). Pieces without cost are not buildable.
static func technology_json(a_registry: RefCounted) -> String:
	var ids: Array = a_registry.pieces.keys()
	ids.sort()
	var table: Dictionary = {}
	for id in ids:
		var spec: Dictionary = a_registry.pieces[id]
		if not spec.has("cost"):
			continue
		var cost: Dictionary = spec["cost"] if spec["cost"] is Dictionary else {}
		var requires: Array = []
		for r in spec.get("requires", []):
			requires.append(str(r))
		table[id] = {
			"cost": {
				"ore": int(cost.get("ore", 0)),
				"vigor": int(cost.get("vigor", 0)),
				"dominion": int(cost.get("dominion", 0)),
			},
			"build_time_ticks": int(roundf(float(spec.get("build_time", 0)) * TICKS_PER_SECOND)),
			"requires": requires,
		}
	return _json_header("technology (cost / build time / prerequisites)") + JSON.stringify(table, "\t") + "\n"


## {command_name: {"id", "scene", "label", "grid", "context"}} for every piece
## with a ui: key. context derives from kind: structures are placed (BUILD),
## units are trained (TRAIN).
static func tools_json(a_registry: RefCounted) -> String:
	var ids: Array = a_registry.pieces.keys()
	ids.sort()
	var table: Dictionary = {}
	for id in ids:
		var spec: Dictionary = a_registry.pieces[id]
		if not spec.has("ui") or not (spec["ui"] is Dictionary):
			continue
		var ui: Dictionary = spec["ui"]
		if not spec.has("scene"):
			continue   # a tool needs a scene to place/train
		var factions: Array = []
		for f in ui.get("factions", []):
			factions.append(str(f))
		table["command_tool_%s" % id] = {
			"id": id,
			"scene": str(spec["scene"]),
			"label": str(ui.get("label", String(id).capitalize())),
			"grid": [int(ui["grid"][0]), int(ui["grid"][1])] if ui.has("grid") else [0, 0],
			"context": "BUILD" if spec["_kind"] == "structure" else "TRAIN",
			"factions": factions,
		}
	return _json_header("build/train tool registry") + JSON.stringify(table, "\t") + "\n"


# --------------------------------------------------------------------------- #
# IO
# --------------------------------------------------------------------------- #
static func _gd_header(a_what: String) -> String:
	return "## AUTO-GENERATED by tools/spec_import (%s).\n## Do not edit by hand — edit the gdd docs and re-run the importer.\n" % a_what


static func _json_header(a_what: String) -> String:
	# JSON has no comments; the marker rides in a reserved "_generated" key? No —
	# consumers iterate keys. The header lives in the sibling .md docs instead;
	# this function exists so a format change stays one-line.
	return ""


static func _write(a_path: String, a_text: String) -> String:
	DirAccess.make_dir_recursive_absolute(a_path.get_base_dir())
	var f: FileAccess = FileAccess.open(a_path, FileAccess.WRITE)
	if f == null:
		push_error("spec_import: cannot write %s" % a_path)
		return a_path
	f.store_string(a_text)
	f.close()
	return a_path
