#!/usr/bin/env python3
"""gdd spec docs -> dh_balance YAML catalogs.

The gdd/ markdown docs (YAML frontmatter, see tools/spec_import/README.md) are
the source of truth for game-piece data; this script derives the catalogs the
``dh_balance`` analysis tool consumes. It REPLACES the retired Godot->YAML
exporter (tools/balance_export): the docs already carry the stats, so no engine
run is needed.

    python3 tools/balance/gdd_to_balance.py     # writes tools/balance/data/

Notes:
  * Faction grouping is by doc DIRECTORY (gdd/factions/<f>/pieces -> faction
    <f>; everything else -> "shared"). In-game faction membership is data-
    decoupled; for balance analysis the authoring layout is the useful grouping.
  * Times in docs are seconds; dh_balance uses 30 tps ticks (converted here).
  * Status-effect numbers aren't doc-governed (the scenes own them), so DoT
    stats are read straight out of the effect scene files.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent.parent
GDD = REPO / "gdd"
DATA = Path(__file__).resolve().parent / "data"
DAMAGE_DIR = REPO / "resources" / "damage"

TICKS = 30

HEADER = "# AUTO-GENERATED by tools/balance/gdd_to_balance.py from the gdd/ spec docs.\n# Do not edit by hand; edit the docs and re-run.\n"


def frontmatter(path: Path) -> dict | None:
    lines = path.read_text().split("\n")
    if not lines or lines[0].strip() != "---":
        return None
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() in ("---", "..."))
    except StopIteration:
        return None
    data = yaml.safe_load("\n".join(lines[1:end])) or {}
    # Discovery mirrors the Godot importer: a doc is a spec iff it has an `id`.
    return data if isinstance(data, dict) and "id" in data else None


def wl(value):
    """Strip Obsidian wikilink syntax from a scalar reference."""
    if isinstance(value, str):
        m = re.fullmatch(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]", value.strip())
        if m:
            return m.group(1).split("/")[-1].strip()
    return value


def collect_docs() -> dict[str, list[tuple[Path, dict]]]:
    by_kind: dict[str, list[tuple[Path, dict]]] = {}
    for path in sorted(GDD.rglob("*.md")):
        if ".obsidian" in path.parts:
            continue
        data = frontmatter(path)
        if data is None:
            continue
        if "kind" not in data:
            print(f"  WARN: {path.relative_to(REPO)} has an id but no kind — skipped")
            continue
        by_kind.setdefault(str(data["kind"]), []).append((path, data))
    return by_kind


def faction_of(path: Path) -> str:
    """Faction = the gdd/factions/<f>/ directory the doc lives under, at any
    depth below it (units/, structures/, projectiles/, …). Anything outside
    gdd/factions/ is "shared"."""
    parts = path.relative_to(GDD).parts
    if len(parts) >= 3 and parts[0] == "factions":
        return parts[1]
    return "shared"


def status_effect_entry(doc: dict) -> dict:
    """DoT stats live in the effect scene, not the doc — parse the .tscn text."""
    scene = REPO / str(doc["scene"]).replace("res://", "")
    entry: dict = {"kind": "status_effect"}
    if scene.exists():
        text = scene.read_text()
        if "damage_over_time_status_effect.gd" in text:
            entry["kind"] = "damage_over_time"
            for key in ("damage_per_tick", "tick_rate", "duration_ticks"):
                m = re.search(rf"^{key} = ([0-9.]+)$", text, re.M)
                if m:
                    entry[key] = float(m.group(1)) if "." in m.group(1) else int(m.group(1))
            m = re.search(r"^damage_type = (\d+)$", text, re.M)
            entry["damage_type"] = DAMAGE_TYPES[int(m.group(1))] if m else "LEAD"
        elif "suicide_status_effect.gd" in text:
            entry["kind"] = "suicide"
    return entry


DAMAGE_TYPES = ["UNDEFINED", "LEAD", "TOXIC", "SONIC", "PLASMA", "SIEGE", "EXPLOSIVE", "ELECTRIC", "LAZER"]


def projectile_entry(doc: dict) -> dict:
    """Catalog entry for a projectile. Standalone `kind: projectile` docs and a
    weapon's inline `projectile:` mapping use the same field names, so both
    shapes come through here."""
    return {
        "base_damage": doc.get("damage", 0),
        "damage_type": doc.get("damage_type", "LEAD"),
        "speed": doc.get("speed", 0),
        "status_effects": [wl(s) for s in (doc.get("status_effects") or [])],
    }


def weapon_entries(piece: dict) -> tuple[list[str], dict[str, dict], dict[str, dict]]:
    """-> (weapon ids, weapon catalog, projectile catalog).

    A weapon's `projectile:` is either a REFERENCE to a standalone projectile
    doc or an INLINE mapping defining one. Inline ones are lifted into the
    projectile catalog here, so downstream every weapon links by id.
    """
    ids, catalog, projectiles = [], {}, {}
    for w in piece.get("weapons") or []:
        wid = f"{piece['id']}_{re.sub(r'[^a-z0-9]+', '_', str(w.get('name', 'weapon')).lower()).strip('_')}"
        entry: dict = {"name": w.get("name", wid)}
        projectile = w.get("projectile")
        if isinstance(projectile, dict):
            pid = str(projectile["id"])
            projectiles[pid] = projectile_entry(projectile)
            entry["projectile"] = pid
        elif projectile:
            entry["projectile"] = wl(projectile)
        else:
            entry["melee_damage"] = w.get("melee_damage", 0)
            entry["melee_damage_type"] = w.get("melee_damage_type", "LEAD")
        entry["split_time"] = int(round(float(w.get("split_time", 1)) * TICKS))
        entry["reload_time"] = int(round(float(w.get("reload_time", w.get("split_time", 1))) * TICKS))
        entry["clip_size"] = int(w.get("clip_size", 1))
        reach = w.get("reach", 0)
        entry["reach"] = float(reach.get("ground", reach.get("air", 0))) if isinstance(reach, dict) else float(reach)
        entry["hits"] = [str(h) for h in (w.get("hits") or ["ground"])]
        ids.append(wid)
        catalog[wid] = entry
    return ids, catalog, projectiles


def producer_of_map(docs: dict[str, list[tuple[Path, dict]]]) -> dict[str, list[str]]:
    """Invert structure `trains:` frontmatter into unit id -> producer structure ids."""
    out: dict[str, list[str]] = {}
    for _, d in docs.get("structure", []):
        for unit_id in (d.get("trains") or []):
            out.setdefault(wl(unit_id), []).append(d["id"])
    return out


def buildable_entry(piece: dict, weapon_ids: list[str], producer_of: dict[str, list[str]]) -> dict:
    cost = piece.get("cost") or {}
    requires = [wl(r) for r in (piece.get("requires") or [])]
    for producer_id in producer_of.get(piece["id"], []):
        if producer_id not in requires:
            requires.append(producer_id)
    entry: dict = {
        "id": piece["id"],
        "kind": piece["kind"],
        "name": piece.get("title")
        or (piece.get("ui") or {}).get("label")
        or str(piece["id"]).replace("_", " ").title(),
        "cost": {"ore": int(cost.get("ore", 0)),
                 "population": int(cost.get("vigor", 0)),
                 "dominion": int(cost.get("dominion", 0))},
        "requires": requires,
        # Which structures this piece can construct. NOT a requires edge: a
        # builder is the entry point to its structures, not a prerequisite of
        # them, so these seed the tech graph's sources (see graph.reachable_from).
        "builds": [wl(b) for b in (piece.get("builds") or [])],
    }
    if piece.get("armour"):
        entry["armour"] = piece["armour"]
    if piece.get("frame"):
        entry["frame"] = piece["frame"]
    if piece.get("hp") is not None:
        entry["hp"] = piece["hp"]
    movement = piece.get("movement") or {}
    if movement:
        layer = "air" if str(movement.get("mode", "")).upper() in ("HOVERING", "FLYING") else "ground"
        entry["movement"] = {"layer": layer, "speed": float(movement.get("speed", 0))}
    entry["attributes"] = []
    entry["weapons"] = weapon_ids
    return entry


VALID_DAMAGE_ROWS = set(DAMAGE_TYPES) - {"UNDEFINED"}


def load_tsv(path: Path) -> dict:
    rows = [line.split("\t") for line in path.read_text().splitlines() if line.strip()]
    cols = [c.strip() for c in rows[0][1:]]
    table = {}
    for row in rows[1:]:
        name = row[0].strip()
        if not name:
            continue
        if name not in VALID_DAMAGE_ROWS:
            # e.g. the TSV's stale "TOXIN" row (the enum says TOXIC) — the game
            # ignores unknown rows the same way, so mirror that here.
            print(f"  WARN: {path.name}: '{name}' is not a Damage.Type — row skipped")
            continue
        entry = {}
        for i, cell in enumerate(row[1:]):
            if i < len(cols) and cell.strip():
                entry[cols[i]] = float(cell)
        table[name] = entry
    return table


def dump(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + yaml.safe_dump(payload, sort_keys=True, default_flow_style=False))
    print(f"  wrote {path.relative_to(REPO)}")


def main() -> int:
    docs = collect_docs()

    status_effects = {d["id"]: status_effect_entry(d) for _, d in docs.get("status_effect", [])}

    projectiles = {}
    for _, d in docs.get("projectile", []):
        projectiles[d["id"]] = projectile_entry(d)

    producer_of = producer_of_map(docs)

    weapons: dict[str, dict] = {}
    factions: dict[str, dict] = {}
    for path, d in docs.get("unit", []) + docs.get("structure", []):
        wids, wcat, pcat = weapon_entries(d)
        weapons.update(wcat)
        for pid, pentry in pcat.items():
            # A standalone `kind: projectile` doc is the authoritative
            # declaration; an inline mapping reusing its id is ambiguous.
            if pid in projectiles and projectiles[pid] != pentry:
                print(f"  WARN: projectile '{pid}' inline in {d['id']} disagrees with the "
                      f"'{pid}' projectile doc — the doc wins")
                continue
            projectiles[pid] = pentry
        fid = faction_of(path)
        factions.setdefault(fid, {"faction": fid, "name": fid.title(),
                                  "description": "Derived from gdd doc layout by gdd_to_balance.py.",
                                  "buildables": [], "starts_with": []})
        factions[fid]["buildables"].append(buildable_entry(d, wids, producer_of))

    for _, d in docs.get("faction", []):
        if d["id"] in factions:
            factions[d["id"]]["name"] = d.get("title", d.get("name", d["id"]))
            factions[d["id"]]["starts_with"] = [wl(s) for s in (d.get("starts_with") or [])]

    # Regenerate data/ wholesale — it is fully derived now.
    for old in (DATA / "factions").glob("*.yaml"):
        old.unlink()
    for fid, payload in sorted(factions.items()):
        payload["buildables"].sort(key=lambda b: b["id"])
        dump(DATA / "factions" / f"{fid}.yaml", payload)
    dump(DATA / "status_effects.yaml", {"status_effects": status_effects})
    dump(DATA / "projectiles.yaml", {"projectiles": projectiles})
    dump(DATA / "weapons.yaml", {"weapons": weapons})
    dump(DATA / "damage_table.yaml", {
        "vs_armour": load_tsv(DAMAGE_DIR / "damage_vs_armour.tsv"),
        "vs_attribute": load_tsv(DAMAGE_DIR / "damage_vs_attribute.tsv"),
        "vs_frame": load_tsv(DAMAGE_DIR / "damage_vs_frame.tsv"),
    })
    print("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
